import React from 'react';
import { 
  Sparkles, 
  CheckCircle2, 
  AlertCircle, 
  XCircle, 
  BarChart2, 
  FileText, 
  Briefcase, 
  BookOpen, 
  HelpCircle,
  TrendingUp,
  Award,
  Layers
} from 'lucide-react';

export const DocumentAnalyticsDashboard = ({ documentData }) => {
  if (!documentData) return null;

  const score = documentData.overallScore || 80;
  const breakdown = documentData.scoreBreakdown || {
    grammar: 85,
    spelling: 90,
    formatting: 85,
    structure: 80,
    readability: 85,
    completeness: 80
  };

  const summary = documentData.summary || {
    grammar: 0,
    spelling: 0,
    formatting: 0,
    structure: 0,
    readability: 0,
    characterOcr: 0
  };

  const totalIssues = Object.values(summary).reduce((a, b) => a + b, 0);

  // Determine circular progress stroke color
  const getScoreColor = (sc) => {
    if (sc >= 85) return '#10b981'; // Emerald
    if (sc >= 70) return '#6366f1'; // Indigo
    if (sc >= 50) return '#f59e0b'; // Amber
    return '#ef4444'; // Red
  };

  const scoreColor = getScoreColor(score);
  const strokeDash = `${score}, 100`;

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      
      {/* Top Banner: Score & Executive Quality Rating */}
      <div 
        className="glass-panel p-6 sm:p-8 rounded-3xl relative overflow-hidden border"
        style={{ borderColor: 'var(--bg-card-border)' }}
      >
        <div 
          className="absolute -right-16 -top-16 w-64 h-64 rounded-full blur-3xl opacity-20 pointer-events-none"
          style={{ background: 'var(--gradient-hero)' }}
        />

        <div className="flex flex-col lg:flex-row items-center justify-between gap-8 relative z-10">
          
          {/* Left: Overall Quality Indicator */}
          <div className="flex flex-col sm:flex-row items-center gap-6 text-center sm:text-left">
            
            {/* Circular Gauge */}
            <div className="relative w-32 h-32 flex items-center justify-center shrink-0">
              <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
                <path
                  className="text-slate-800"
                  strokeWidth="3.2"
                  stroke="currentColor"
                  fill="none"
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                />
                <path
                  strokeDasharray={strokeDash}
                  strokeWidth="3.5"
                  strokeLinecap="round"
                  stroke={scoreColor}
                  fill="none"
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                />
              </svg>
              <div className="absolute flex flex-col items-center justify-center text-center">
                <span className="text-3xl font-black tracking-tight" style={{ color: 'var(--text-primary)' }}>
                  {score}
                </span>
                <span className="text-[10px] uppercase font-bold text-slate-400">/ 100</span>
              </div>
            </div>

            <div className="space-y-1.5">
              <div className="flex items-center justify-center sm:justify-start gap-2">
                <span className="text-xs font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full border bg-indigo-500/10 border-indigo-500/20 text-indigo-400">
                  {documentData.documentType?.toUpperCase()} AUDIT
                </span>
                <span className="text-xs" style={{ color: 'var(--text-muted)' }}>
                  {documentData.wordCount || 0} words • {documentData.pageCount || 1} pages
                </span>
              </div>

              <h2 className="text-2xl font-black" style={{ color: 'var(--text-primary)' }}>
                {score >= 85 ? '🌟 Excellent Document Quality' : score >= 70 ? '👍 Good with Improvement Areas' : '⚠️ Multiple Corrections Needed'}
              </h2>
              <p className="text-xs max-w-xl" style={{ color: 'var(--text-secondary)' }}>
                Overall Document Score generated by EduFriend AI. Use this as a comprehensive quality and proofreading indicator before academic submission or job applications.
              </p>
            </div>
          </div>

          {/* Right: Quick Issue Counts */}
          <div className="flex items-center gap-4 bg-slate-900/40 border border-white/10 p-4 rounded-2xl shrink-0">
            <div className="text-center px-2">
              <p className="text-2xl font-extrabold text-rose-400">{totalIssues}</p>
              <p className="text-[10px] uppercase font-bold text-slate-400">Total Issues</p>
            </div>
            <div className="w-[1px] h-8 bg-white/10" />
            <div className="text-center px-2">
              <p className="text-2xl font-extrabold text-indigo-400">{summary.grammar + summary.spelling}</p>
              <p className="text-[10px] uppercase font-bold text-slate-400">Grammar & Spell</p>
            </div>
            <div className="w-[1px] h-8 bg-white/10" />
            <div className="text-center px-2">
              <p className="text-2xl font-extrabold text-cyan-400">{summary.formatting + summary.characterOcr}</p>
              <p className="text-[10px] uppercase font-bold text-slate-400">Format & OCR</p>
            </div>
          </div>

        </div>
      </div>

      {/* Category Breakdown & Progress Bars */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-4">
        {[
          { label: 'Grammar', score: breakdown.grammar, issues: summary.grammar, icon: '📝', color: 'from-blue-500 to-indigo-600' },
          { label: 'Spelling', score: breakdown.spelling, issues: summary.spelling, icon: '🔤', color: 'from-purple-500 to-pink-500' },
          { label: 'Formatting', score: breakdown.formatting, issues: summary.formatting, icon: '📐', color: 'from-cyan-500 to-blue-500' },
          { label: 'Structure', score: breakdown.structure, issues: summary.structure, icon: '🏗️', color: 'from-teal-500 to-emerald-500' },
          { label: 'Readability', score: breakdown.readability, issues: summary.readability, icon: '💡', color: 'from-amber-500 to-orange-500' },
          { label: 'OCR / Scan', score: Math.max(70, 96 - summary.characterOcr * 5), issues: summary.characterOcr, icon: '📷', color: 'from-violet-500 to-purple-600' }
        ].map((item) => (
          <div 
            key={item.label}
            className="glass-panel p-4 rounded-2xl space-y-2 border"
            style={{ borderColor: 'var(--bg-card-border)' }}
          >
            <div className="flex items-center justify-between">
              <span className="text-base">{item.icon}</span>
              <span className="text-xs font-bold" style={{ color: 'var(--text-primary)' }}>
                {item.score}%
              </span>
            </div>
            <div>
              <p className="text-xs font-semibold" style={{ color: 'var(--text-primary)' }}>
                {item.label}
              </p>
              <p className="text-[11px]" style={{ color: item.issues > 0 ? '#f59e0b' : '#10b981' }}>
                {item.issues > 0 ? `${item.issues} issues detected` : 'No issues found'}
              </p>
            </div>
            <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden">
              <div 
                className={`h-full rounded-full bg-gradient-to-r ${item.color}`}
                style={{ width: `${item.score}%` }}
              />
            </div>
          </div>
        ))}
      </div>

      {/* Special Module: Assignment Structure OR Resume Health OR Study Notes */}
      {documentData.documentType === 'assignment' && documentData.structureAnalysis && (
        <div 
          className="glass-panel p-5 rounded-2xl border space-y-3"
          style={{ borderColor: 'var(--bg-card-border)' }}
        >
          <div className="flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-indigo-400" />
            <h4 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>
              Assignment Structure Audit
            </h4>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3 text-xs">
            {[
              { name: 'Introduction', state: documentData.structureAnalysis.introduction },
              { name: 'Main Content', state: documentData.structureAnalysis.mainContent },
              { name: 'Examples / Proofs', state: documentData.structureAnalysis.examples },
              { name: 'Conclusion', state: documentData.structureAnalysis.conclusion },
              { name: 'References / Citations', state: documentData.structureAnalysis.references }
            ].map((sec) => (
              <div 
                key={sec.name}
                className="p-3 rounded-xl border flex items-center justify-between"
                style={{
                  backgroundColor: 'var(--bg-canvas-subtle)',
                  borderColor: 'var(--bg-card-border)'
                }}
              >
                <span className="font-semibold" style={{ color: 'var(--text-primary)' }}>{sec.name}</span>
                <span>
                  {sec.state === 'good' ? '✅' : sec.state === 'needs_improvement' ? '⚠️' : '❌'}
                </span>
              </div>
            ))}
          </div>
          {documentData.structureAnalysis.notes && (
            <p className="text-xs text-slate-400 italic">
              💡 {documentData.structureAnalysis.notes}
            </p>
          )}
        </div>
      )}

      {documentData.documentType === 'resume' && documentData.resumeHealth && (
        <div 
          className="glass-panel p-5 rounded-2xl border space-y-3"
          style={{ borderColor: 'var(--bg-card-border)' }}
        >
          <div className="flex items-center gap-2">
            <Briefcase className="w-4 h-4 text-cyan-400" />
            <h4 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>
              Resume Health & ATS Completeness Report
            </h4>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-6 gap-2 text-xs">
            {[
              { label: 'Contact Info', ok: documentData.resumeHealth.contactInfo },
              { label: 'Objective', ok: documentData.resumeHealth.careerObjective },
              { label: 'Education', ok: documentData.resumeHealth.education },
              { label: 'Skills', ok: documentData.resumeHealth.skills },
              { label: 'Projects', ok: documentData.resumeHealth.projects },
              { label: 'Experience', ok: documentData.resumeHealth.experience }
            ].map((item) => (
              <div 
                key={item.label}
                className={`p-2.5 rounded-xl border text-center font-medium ${
                  item.ok ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-rose-500/10 border-rose-500/20 text-rose-400'
                }`}
              >
                {item.ok ? '✓ ' : '✕ '} {item.label}
              </div>
            ))}
          </div>

          {documentData.resumeHealth.recommendations && (
            <div className="pt-2 space-y-1 text-xs">
              <span className="font-bold text-indigo-400">AI Career Suggestions:</span>
              <ul className="list-disc list-inside text-slate-300 space-y-0.5">
                {documentData.resumeHealth.recommendations.map((rec, i) => (
                  <li key={i}>{rec}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {documentData.documentType === 'notes' && documentData.studyNotesEnhancement && (
        <div 
          className="glass-panel p-5 rounded-2xl border space-y-3"
          style={{ borderColor: 'var(--bg-card-border)' }}
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Award className="w-4 h-4 text-amber-400" />
              <h4 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>
                Study Notes Key Highlights
              </h4>
            </div>
            <span className="text-xs px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              Exam-Ready Summary
            </span>
          </div>

          <div className="flex flex-wrap gap-2 text-xs">
            {documentData.studyNotesEnhancement.keyConcepts?.map((c, i) => (
              <span key={i} className="px-3 py-1 rounded-lg bg-indigo-500/10 text-indigo-300 border border-indigo-500/20">
                📌 {c}
              </span>
            ))}
          </div>
        </div>
      )}

    </div>
  );
};
